title: problme
email: richard.muffler@gmail.com
description: Resume and Product Management blog.
author: Richard Robitaille-Muffler
baseurl: "/problme"
url: "https://probl.me"
show_downloads: false
google_analytics: UA-142594739-1
theme: jekyll-theme-cayman
plugins:
  - jekyll-seo-tag
