title:             ProblMe
email:             richard.muffler@gmail.com
description:       Building a website
author:            Richard Robitaille-Muffler
baseurl:           "/problme"
url:               "http://rustymuffler.github.io"

# Social Profiles
twitter_username:
github_username:   rustymuffler
facebook_username:
linkedin_username: richardmuffler

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
